### ISSUE TITLE
move_player

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#11]
### void move_player(PLAYER_T *player)
- 内容
  - プレイヤー1人のターン処理
    - サイコロを投げる
    - 進む
    - ステータスを変更
- 戻り値
  - ナシ
- 呼び出し
  - throw_dice
- 呼びだされ
  - game_main

**Comment by takunoko** [comment]
所持金によって動作を変更する部分が作成できていない．

所持金が
- ある  
  マスの挙動を行う
- ない  
  ステータス変化なし

**Comment by takunoko** [comment]
プルリクマージしたら消しといて！

**Comment by genki-hashimoto** [comment]
あんま重くなかったな！お疲れ！
