### ISSUE TITLE
カレンダー元データcsvの作成

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#14]
# タイトルの通り
## 必要なもの
- デフォルトカレンダー(1)
- 学年別イベントカレンダー(5)
- 部活別イベントカレンダー(2?)
- 彼女持ちイベントカレンダー(1)

計9

**Comment by takunoko** [comment]
テストする際に適当に必要なんで、適当に実装しちゃいます。
内容があるやつができたらまたアップお願いします!

**Comment by genki-hashimoto** [comment]
認識スレ違いでベースカレンダーは実装されていますが存在はしないので，ダミーのカレンダーを読み込み学年カレンダーで全てを上書きします．

**Comment by genki-hashimoto** [comment]
@NatsumiJibiki バイトをしても彼女とデートをしても課題が減っていたりと違和感があるポイントが非常に多いので元気だったら手動でポイントを振っていただけるとゲーム性が増します．
必須ではありません．
