### ISSUE TITLE
var.h

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#2]
すべての構造体定義がされるヘッダファイル

**Comment by genki-hashimoto** [comment]
var.h確認お願いします

**Comment by takunoko** [comment]
名前を保持する場所がなかった。
適当に付け加えておきます。

ブランチもそれっぽいのが残ってないので、新しく1を切ります

**Comment by takunoko** [comment]
とりあえず問題なさそうだからClose
これ以上変更がない事を祈って…。
