### ISSUE TITLE
init_players

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#4]
### int init_players(PLAYER_T *players)
- 内容
  - プレイヤー全員の初期化
- 戻り値
  - 正常終了→TRUE
  - エラー発生→FALSE
- 呼び出し
  - init_player

**Comment by takunoko** [comment]
たぶんできてるから、誰か確認して…。

**Comment by takunoko** [comment]
何人目のプレイヤーが入力してるか、現状では判別不可能。

ゲームとして実装するときになんとかしよう！

**Comment by takunoko** [comment]
init_playerの表示との兼ね合いを考えながら何人目のプレイヤーを初期化しているのか表示する機能の実装が必要!

**Comment by genki-hashimoto** [comment]
これ表示するようになったから閉じてもいい？？？

**Comment by takunoko** [comment]
おっ，そうだ．
closeしま〜す．
