### ISSUE TITLE
イベント内容表示最初の一巡(要検証)が表示されない

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#58]
# 原因

不明．究明求ム
# 対処法

不明．

**Comment by takunoko** [comment]
気のせいか，プレイヤー4人中1人の行動予定or4回に1回しかイベント内容が表示されてない気がする．
@EbLicht お兄さん氏〜〜〜〜

**Comment by takunoko** [comment]
マージされてると思うんでcloseします〜
