### ISSUE TITLE
名前の入力について

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#61]
やはり制限するべきかと
<img width="531" alt="2016-02-17 17 40 17" src="https://cloud.githubusercontent.com/assets/6134022/13103996/cbd04cf8-d59d-11e5-814d-ab255fa5ab6f.png">
<img width="534" alt="2016-02-17 17 40 35" src="https://cloud.githubusercontent.com/assets/6134022/13103997/ce58fdb2-d59d-11e5-9e11-80744ecb951b.png">

**Comment by takunoko** [comment]
制限をつける場合に，日本語文字数と英語文字数で判断(日本語ならn文字，アルファベットならm文字みたいな)できないから，日本語でも問題ない文字数に制限でいいかな？

**Comment by genki-hashimoto** [comment]
それは有りだと思う．ただ必須ではないので適当でお願いします！明日のうちにレポートにソース埋め込みたいから放課後までに修正しなくていいやってなったら対応しませんラベルつけてクローズしましょう

**Comment by takunoko** [comment]
了解です．
頑張ります．

**Comment by takunoko** [comment]
日本語3バイトでカウントされるっぽくて，半角文字なら17文字入るので，
15バイト(日本語なら5文字，半角文字なら15文字)で制限します．

**Comment by genki-hashimoto** [comment]
b

**Comment by genki-hashimoto** [comment]
対応しました！江澤ありがとう！
