### ISSUE TITLE
init_cursesについて

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#62]
voidだし特に引数もないのであれば，programinit()で実行したほうがすっきりする気もしますがどうでしょうか

**Comment by takunoko** [comment]
確かに．
programinit()で利用する場所がないから気づかなかったのだけど，確かにprograminit()で実行して良さそう．

ただ，わんちゃんinit_curses()を実行した後にデバッグでprintfを使うようなテストプログラムがあるとprintfが表示されないみたいな謎現象が発生しそうでもある．

**Comment by genki-hashimoto** [comment]
では必須ではないのでこのままにしましょう！クローズします
