### ISSUE TITLE
set_player_status

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#7]
### void set_player_status(int *grade, int *club, int *girlfriend)
- 内容
  - 学年，部活，彼女を初期化
  - 学年と部活は入力から(エラー入力はやりなおし)
  - 彼女は乱数で決定
- 戻り値
  - ナシ
- 呼びだされ
  - init_player

**Comment by takunoko** [comment]
#5 でまとめて実装してしまいましたm(_ _)m
彼女乱数の部分がきちんと実装されてないので、他のissuesで対応しよう!
