### ISSUE TITLE
init_calender

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#8]
### void init_calender(TROUT_T *calender, int grade, int club, int girlfriend))
- 内容
  - プレイヤー固有のカレンダーを初期化
- 戻り値
  - ナシ
- 呼びだされ
  - init_player
## ゲーム中関数群

はじまってからの関数たち

**Comment by takunoko** [comment]
↑ PLAYER_T *player を引数として持ってない (・_・)
