### ISSUE TITLE
game_main

### ISSUE THREAD

**Issue by genki-hashimoto** [SoftwareGroup2/XXXNatsu#9]
### void game_main(PLAYER_T *players)
- 内容
  - 二重ループを回す
  - 一重目は全員がゴールするまで
    - 二重目ループ
    - イベントの発生
  - 二重目は全員が一週間終わるまで
    - 一番遅い人を調べる関数
    - 1ターンの処理
- 戻り値
  - ナシ
- 呼び出し
  - select_active_player
- 呼びだされ
  - main

**Comment by takunoko** [comment]
#### 2/17 追記
- 課題ポイントがイベントでマイナス値をとる時に0にする
- ゲーム終了画面での名前を別表示して合わせる．

**Comment by takunoko** [comment]
無事にできたんで，あとはバグ取りぐらいってことでcloseしますね〜
